# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-10 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20170909_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=0, verbose_name='是否轮播'),
        ),
    ]
