# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-07 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170831_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='用户名1'),
        ),
    ]
