# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-10 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170910_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nickname',
            new_name='nick_name',
        ),
    ]
